### ISSUE TITLE
Enchanted Harvester on contraption crashes the game when harvesting farmers delights crop.

### ISSUE THREAD

**Issue by GammaNo0b** [cotrin8672/CreateEnchantableMachinery#65]
**Describe the bug**
When powering a contraption with an enchanted harvester and storage and the harvester harvests a farmers delight crop, the game crashes.

**Environment**
Minecraft version :  1.20.1
fabric api : 0.92.2+1.20.1
create enchantable machinery : 1.20.1-2.8.6
farmers delight refabricated : 1.20.1-2.2.4
fabric language kotlin : 1.13.0+kotlin.2.1.0

**To Reproduce**
1. Enchant Harvester (I did it with fortune 3)
2. Build contraption with storage (I used a barrel) (both rotating contraption and linear using piston crashed)
3. Plant tomato crop (farmers delight)  so that the harvester will harvest it and bonemeal it to it's maximum age.
4. Power Contraption -> Game Crashes on harvest

**Expected behavior**
Game does not crash.

**Additional Notes**
The crash did not occur, when using an unenchanted harvester.
The crash also did not occur when harvesting wheat seeds, only the tomato seeds (I didn't tested other vanilla / farmers delight crops).
The crash only occurred when using a barrel (or storage in general) on the contraption. Otherwise the tomato correctly just dropped it crops.

**Stacktrace**
java.lang.IllegalArgumentException: Transfer variant may not be blank.
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
	at io.github.fabricators_of_create.porting_lib.transfer.item.ItemStackHandler.insert(ItemStackHandler.java:63)
	at io.github.fabricators_of_create.porting_lib.transfer.item.ItemStackHandler.insert(ItemStackHandler.java:35)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:67)
	at com.simibubi.create.content.contraptions.behaviour.MovementBehaviour.dropItem(MovementBehaviour.java:61)
	at io.github.cotrin8672.content.block.harvester.EnchantableHarvesterMovementBehaviour.visitNewPosition$lambda$2(EnchantableHarvesterMovementBehaviour.java:76)
	at com.simibubi.create.foundation.utility.BlockHelper.destroyBlockAs(BlockHelper.java:172)
	at io.github.cotrin8672.content.block.harvester.EnchantableHarvesterMovementBehaviour.visitNewPosition(EnchantableHarvesterMovementBehaviour.java:68)
	at com.simibubi.create.content.contraptions.AbstractContraptionEntity.tickActors(AbstractContraptionEntity.java:474)
	at com.simibubi.create.content.contraptions.ControlledContraptionEntity.tickContraption(ControlledContraptionEntity.java:156)
	at com.simibubi.create.content.contraptions.AbstractContraptionEntity.method_5773(AbstractContraptionEntity.java:388)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by cotrin8672** [comment]
Thank you for your report!
I have identified the problem and will fix it in the next update.
